"""Public demo build: assemble `portfolio/` from the real frontend plus frozen API responses (D-046).

GitHub Pages serves static files only, so the published build keeps the *same* frontend
(``src/ensemble/api/static``) and answers its requests from responses captured once from the local
application. Two phases, so only one of them needs the data:

  python -m ensemble.api.public_demo sync      # frontend -> portfolio/ (deterministic, no network, no DB)
  python -m ensemble.api.public_demo capture   # frozen responses + catalogue photography (needs `make serve`)
  python -m ensemble.api.public_demo build     # capture, then sync

``capture`` reads the serving store only to choose *which* articles to publish; every published value
comes back over HTTP from the running application, unchanged. Responses that a language model produces
(the Style Assistant turns and the outfit analysis) are captured once and then reused, so a rebuild does
not silently replace a published answer; ``--force`` re-captures them.

Nothing here feeds a model, a feature or an evaluation.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import sqlite3
import sys
import urllib.error
import urllib.parse
import urllib.request
import uuid
from collections import Counter
from pathlib import Path

import yaml

from ensemble.config import load_config

ROOT = Path(__file__).resolve().parents[3]
STATIC = Path(__file__).parent / "static"
DEMO_CONFIG = ROOT / "configs" / "public_demo.yaml"
IMAGE_RE = re.compile(r"^/?images/(\d+)\.jpg$")   # also matches an already-published path, so a rebuild is idempotent

# Injected into the published index.html; the real one carries neither.
DEMO_META = '<meta name="ensemble-demo" content="{fixtures}/">'
FOOTER_NOTE = (
    '<p class="footer__note">This is the interface of the local application, published with stored '
    'responses captured from it. It runs no models and records nothing. '
    '<a href="https://github.com/yilalalalala/ensemble-outfit-recommender">Source and evaluation reports</a></p>'
)
GENERATED = "<!-- Generated by `python -m ensemble.api.public_demo sync`. Edit src/ensemble/api/static instead. -->"


def demo_config(path: Path | None = None) -> dict:
    return yaml.safe_load((path or DEMO_CONFIG).read_text())


# ---------------------------------------------------------------- sync (deterministic, offline)
def _relativize(html: str, fixtures: str) -> str:
    """The published page declares demo mode and names the site it came from. Asset URLs in the real
    index.html are already document-relative, so they work at `/` and under `/<project>/` alike."""
    assert '<meta name="ensemble-demo"' not in html, "the real index.html must not declare demo mode"
    assert 'href="/static/' not in html and 'src="/static/' not in html, "asset URLs must be document-relative"
    html = html.replace("<head>\n", f"<head>\n{GENERATED}\n" + DEMO_META.format(fixtures=fixtures) + "\n", 1)
    marker = '    <nav class="footer__nav"'
    assert marker in html
    return html.replace(marker, "    " + FOOTER_NOTE + "\n" + marker, 1)


def _write(path: Path, data: bytes) -> bool:
    """Write only on change, so a no-op sync leaves every mtime alone."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_bytes() == data:
        return False
    path.write_bytes(data)
    return True


def sync(cfg: dict, out: Path | None = None) -> dict:
    """Copy the real frontend into the published build. Pure function of src/ensemble/api/static."""
    out = out or ROOT / cfg["out"]
    out.mkdir(parents=True, exist_ok=True)
    written, kept = [], []
    # Everything under static/ is served from static/ in the build too, so the page's own
    # relative URLs are already correct.
    for src in sorted(STATIC.rglob("*")):
        if src.is_dir() or src.name == "index.html":
            continue
        dst = out / "static" / src.relative_to(STATIC)
        (written if _write(dst, src.read_bytes()) else kept).append(str(dst.relative_to(out)))
    index = _relativize((STATIC / "index.html").read_text(), cfg["fixtures"]).encode()
    (written if _write(out / "index.html", index) else kept).append("index.html")
    # The site icon is referenced from static/, but a bare /favicon.svg request is cheap to satisfy.
    (written if _write(out / "favicon.svg", (STATIC / "favicon.svg").read_bytes()) else kept).append("favicon.svg")
    (written if _write(out / ".nojekyll", b"") else kept).append(".nojekyll")
    # Anything left over from an earlier frontend is removed, so the build is the frontend and nothing else.
    expected = set(written) | set(kept)
    removed = []
    for p in sorted((out / "static").rglob("*"), reverse=True):
        rel = str(p.relative_to(out))
        if p.is_file() and rel not in expected:
            p.unlink()
            removed.append(rel)
        elif p.is_dir() and not any(p.iterdir()):
            p.rmdir()
    return {"written": written, "kept": kept, "removed": removed, "files": sorted(expected)}


# ---------------------------------------------------------------- capture (needs the running app)
class Api:
    def __init__(self, base: str):
        self.base = base.rstrip("/")
        self.calls = 0

    def get(self, path: str):
        self.calls += 1
        with urllib.request.urlopen(self.base + path, timeout=120) as r:
            return json.load(r)

    def get_or_none(self, path: str):
        try:
            return self.get(path)
        except urllib.error.HTTPError as e:
            if e.code in (404, 422, 503):
                return None
            raise

    def post_json(self, path: str, body: dict):
        self.calls += 1
        req = urllib.request.Request(self.base + path, data=json.dumps(body).encode(),
                                     headers={"Content-Type": "application/json"}, method="POST")
        with urllib.request.urlopen(req, timeout=900) as r:
            return json.load(r)

    def post_form(self, path: str, fields: dict, files: dict | None = None, timeout: int = 900):
        """multipart/form-data without a dependency: the assistant and photo endpoints take forms."""
        self.calls += 1
        boundary = uuid.uuid4().hex
        body = b""
        for k, v in fields.items():
            body += (f"--{boundary}\r\nContent-Disposition: form-data; name=\"{k}\"\r\n\r\n{v}\r\n").encode()
        for k, (name, data, ctype) in (files or {}).items():
            body += (f"--{boundary}\r\nContent-Disposition: form-data; name=\"{k}\"; filename=\"{name}\"\r\n"
                     f"Content-Type: {ctype}\r\n\r\n").encode() + data + b"\r\n"
        body += f"--{boundary}--\r\n".encode()
        req = urllib.request.Request(self.base + path, data=body, method="POST",
                                     headers={"Content-Type": f"multipart/form-data; boundary={boundary}"})
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return json.load(r)


def rewrite_images(obj, seen: set[int]):
    """Rewrite every ``/images/<id>.jpg`` to the published, document-relative path and record the id."""
    if isinstance(obj, dict):
        return {k: rewrite_images(v, seen) for k, v in obj.items()}
    if isinstance(obj, list):
        return [rewrite_images(v, seen) for v in obj]
    if isinstance(obj, str):
        m = IMAGE_RE.match(obj)
        if m:
            seen.add(int(m.group(1)))
            return f"images/{int(m.group(1))}.jpg"
    return obj


def dump(path: Path, obj) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, sort_keys=True, ensure_ascii=False, separators=(",", ":")) + "\n")


def card_ids(items) -> list[int]:
    out = []
    for it in items or []:
        a = it.get("article_id") if isinstance(it, dict) else None
        if a is not None:
            out.append(int(a))
    return out


def ctl_ids(resp) -> list[int]:
    return [int(it["article_id"]) for m in (resp or {}).get("modules", []) for it in m["items"]]


def filter_ctl(resp: dict, keep: set[int], min_items: int) -> dict:
    """Publish the live response filtered to published articles, in its own order. Modules that fall
    below the floor are dropped, never padded."""
    mods = []
    for m in resp["modules"]:
        items = [it for it in m["items"] if int(it["article_id"]) in keep]
        if len(items) < min_items:
            continue
        mods.append({**m, "items": [{**it, "rank": i + 1} for i, it in enumerate(items)]})
    return {**resp, "request_id": "stored", "modules": mods}


def capture(cfg: dict, force: bool = False, out: Path | None = None, recapture: set[str] | None = None) -> dict:
    """Freeze the responses the published build serves. Everything published comes back over HTTP
    from the running application; the serving store is read only to choose *which* articles."""
    from PIL import Image

    out = out or ROOT / cfg["out"]
    fx = out / cfg["fixtures"]
    img_dir = out / cfg["images"]
    cat = cfg["catalog"]
    api = Api(cfg["capture"]["base"])
    ec = load_config()
    con = sqlite3.connect(f"file:{ec.path('serving_db')}?mode=ro", uri=True)
    con.row_factory = sqlite3.Row
    imgs: set[int] = set()

    try:
        api.get("/readyz")
    except Exception as e:  # noqa: BLE001 - the only external dependency of the build
        port = urllib.parse.urlparse(api.base).port
        raise SystemExit(f"the local application is not reachable at {api.base}: {e}\n"
                         f"start it with `PYTHONPATH=src .venv/bin/uvicorn ensemble.api.app:app "
                         f"--port {port}` and run this again") from None

    customers = [int(c) for c in cfg["customers"]]
    all_customers = {c["customer_idx"]: dict(c) for c in api.get("/api/customers")}
    missing = [c for c in customers if c not in all_customers]
    if missing:
        raise SystemExit(f"configured demo customers are not in the serving store: {missing}")

    # ---- 1. the home modules of every published profile define the core articles
    homes = {c: api.get(f"/api/home/{c}") for c in customers}
    core: set[int] = set()
    for h in homes.values():
        for m in h["modules"]:
            core.update(card_ids(m["items"]))

    # ---- 2. the Style Assistant turns and the two photo services, captured before the article set
    #         is chosen, so every product a saved answer cites is published with it.
    examples, assistant_ids = capture_assistant(api, cfg, fx, force, recapture or set())
    photo, photo_ids = capture_photo(api, cfg, fx, out, ec, force or "photo" in (recapture or set()))

    # ---- 3. Complete the Look for every core anchor, guest and per published profile
    k = cat["ctl_k"]
    ctl: dict[str, dict] = {}
    freq: Counter[int] = Counter()
    for a in sorted(core):
        guest = api.get_or_none(f"/api/v2/complete-the-look?anchor={a}&k={k}")
        if guest:
            ctl[f"{a}"] = guest
            freq.update(ctl_ids(guest))
    for c in customers:
        fy = next((m for m in homes[c]["modules"] if m["id"] == "for_you"), {"items": []})
        for a in sorted(card_ids(fy["items"])):
            r = api.get_or_none(f"/api/v2/complete-the-look?anchor={a}&k={k}&customer={c}")
            if r:
                ctl[f"{a}-{c}"] = r
                freq.update(ctl_ids(r))

    # ---- 4. the published article set: the core, everything a saved answer cites, the most-used
    #         complementary items, and the colourways of all of those
    pool = core | assistant_ids | photo_ids | {a for a, _ in freq.most_common(cat["ctl_pool"])}
    codes: dict[int, str] = {}
    raw_families: dict[str, dict] = {}
    batch = sorted(pool)
    for i in range(0, len(batch), 200):                       # the endpoint caps a request at 400 ids
        fam = api.get("/api/catalog/families?articles=" + ",".join(str(x) for x in batch[i:i + 200]))
        codes.update({int(x): c for x, c in fam["articles"].items()})
        raw_families.update(fam["families"])
    variants: dict[str, dict] = {}
    for code, fam in sorted(raw_families.items()):
        vs = fam["variants"]
        # A colourway a published card points at always stays; the rest are capped so the build stays
        # small, which is what the card's "+N more colours" link already allows for.
        own = [v for v in vs if int(v["article_id"]) in pool]
        rest = [v for v in vs if int(v["article_id"]) not in pool]
        keep = own + rest[: max(0, cat["max_variants_per_family"] - len(own))]
        variants[code] = rewrite_images({**fam, "variants": keep}, imgs)
    published = set(pool) | {int(v["article_id"]) for f in variants.values() for v in f["variants"]}

    # ---- 5. a product page for every published article, with its modules filtered to published articles
    sim_sql = """SELECT a.article_id, a.prod_name, a.product_type_name, a.colour_group_name,
                        a.index_group_name, a.slot, a.is_jewellery
                 FROM articles a JOIN popularity p USING (article_id)
                 WHERE a.product_type_name = ? AND a.index_group_name = ? AND a.product_code <> ?
                   AND a.article_id IN (%s) ORDER BY p.pop_recent DESC LIMIT ?"""
    pub_list = sorted(published)
    ids_sql = ",".join("?" * len(pub_list))
    shutil.rmtree(fx / "product", ignore_errors=True)
    for a in pub_list:
        d = api.get(f"/api/product/{a}")
        art = d["article"]
        rows = con.execute(sim_sql % ids_sql, (art["product_type_name"], art["index_group_name"],
                                               art["product_code"], *pub_list, cat["similar_k"])).fetchall()
        similar = [dict(r) | {"image": f"/images/{r['article_id']}.jpg"} for r in rows]
        look = []
        for m in d["complete_the_look"]:
            items = [it for it in m["items"] if int(it["article_id"]) in published]
            if len(items) >= cat["min_module_items"]:
                look.append({**m, "items": items})
        colours = [c for c in d["other_colours"] if int(c["article_id"]) in published]
        dump(fx / "product" / f"{a}.json",
             rewrite_images({**d, "complete_the_look": look, "other_colours": colours, "similar": similar}, imgs))

    # ---- 6. Complete the Look for every published anchor that is not a core anchor
    for a in pub_list:
        if f"{a}" not in ctl:
            r = api.get_or_none(f"/api/v2/complete-the-look?anchor={a}&k={k}")
            if r:
                ctl[f"{a}"] = r
    shutil.rmtree(fx / "ctl", ignore_errors=True)
    kept = []
    for name, resp in sorted(ctl.items()):
        f = filter_ctl(resp, published, cat["min_module_items"])
        if f["modules"]:
            dump(fx / "ctl" / f"{name}.json", rewrite_images(f, imgs))
            kept.append(name)
    # The index lets the page ask only for a capture that exists: not every anchor has complementary
    # items, and only a profile's own picks were captured personalized.
    dump(fx / "ctl" / "index.json", kept)
    kept_ctl = len(kept)

    # ---- 7. profiles, home modules, families and explanations
    shutil.rmtree(fx / "home", ignore_errors=True)
    shutil.rmtree(fx / "explain", ignore_errors=True)
    for c, h in homes.items():
        dump(fx / "home" / f"{c}.json", rewrite_images(h, imgs))
        fy = next((m for m in h["modules"] if m["id"] == "for_you"), {"items": []})
        dump(fx / "explain" / f"{c}.json",
             {str(a): rewrite_images(api.get(f"/api/explain/{c}/{a}"), imgs) for a in card_ids(fy["items"])})
    dump(fx / "customers.json", [all_customers[c] for c in customers])
    art_code = dict(codes)
    for code, fam in variants.items():
        for v in fam["variants"]:
            art_code[int(v["article_id"])] = code
    dump(fx / "families.json", {"articles": {str(a): art_code[a] for a in sorted(art_code)},
                                "families": variants})

    # ---- 8. DS Studio: the stored evaluation reports, published unchanged, and the bundle's own status
    dump(fx / "metrics.json", api.get("/api/metrics"))
    dump(fx / "serving.json", {"readyz": api.get("/readyz"), "meta": api.get("/api/v2/meta"),
                               "metrics": api.get("/api/v2/metrics")})

    # ---- 9. the saved answers and photo responses, published whole. Their products are in the
    #         published set by construction (step 2 seeded step 4), so nothing is dropped here;
    #         the check fails the build rather than quietly shortening a published answer.
    assert assistant_ids <= published and photo_ids <= published, \
        sorted((assistant_ids | photo_ids) - published)
    for e in examples:
        e["cards"] = rewrite_images(e["cards"], imgs)
    dump(fx / "assistant.json", {"backend": "ollama", "examples": examples})
    for key in ("visual_search", "snap"):
        photo[key] = rewrite_images(photo[key], imgs)
    dump(fx / "photo.json", photo)

    # ---- 10. catalogue photography, downscaled; nothing outside the published set is copied
    shutil.rmtree(img_dir, ignore_errors=True)
    img_dir.mkdir(parents=True, exist_ok=True)
    raw = ec.path("raw") / "images"
    n_img, missing_img = 0, []
    for a in sorted(imgs):
        s = f"{a:010d}"
        src = raw / s[:3] / f"{s}.jpg"
        if not src.exists():
            missing_img.append(a)
            continue
        im = Image.open(src).convert("RGB")
        im.thumbnail((cat["image_width"], cat["image_width"] * 4))
        im.save(img_dir / f"{a}.jpg", format="JPEG", quality=cat["image_quality"], optimize=True,
                progressive=True)
        n_img += 1

    summary = {"customers": customers, "default_customer": cfg["default_customer"],
               "core_articles": len(core), "assistant_articles": len(assistant_ids),
               "photo_articles": len(photo_ids), "published_articles": len(published),
               "families": len(variants), "ctl_fixtures": kept_ctl, "product_fixtures": len(pub_list),
               "images": n_img, "images_missing": missing_img, "assistant_examples": len(examples),
               "api_calls": api.calls, "bundle_version": stored_bundle(fx), "catalog": cat}
    dump(fx / "manifest.json", summary)
    con.close()
    return summary


def capture_assistant(api: Api, cfg: dict, fx: Path, force: bool, recapture: set[str]) -> tuple[list[dict], set[int]]:
    """One real turn per configured question, frozen verbatim. A turn a language model produced is
    captured once and reused, so a rebuild never silently replaces a published answer."""
    a_cfg = cfg["assistant"]
    existing = {e["id"]: e for e in (json.loads((fx / "assistant.json").read_text())["examples"]
                                     if (fx / "assistant.json").exists() else [])}
    examples, cited, sids = [], set(), {}

    def session_for(q: dict) -> str:
        """One conversation per saved exchange: a question with ``followup_of`` continues its parent's
        conversation, anything else starts a fresh one. Sharing one long conversation across unrelated
        questions degrades the answers, which is not what the local application does."""
        parent = q.get("followup_of")
        if parent and parent in sids:
            return sids[parent]
        customer = q.get("customer", a_cfg.get("customer"))
        sids[q["id"]] = api.post_json("/api/assistant/session",
                                      {"customer_idx": customer})["session_id"]
        return sids[q["id"]]

    for q in a_cfg["questions"]:
        e = existing.get(q["id"])
        if e is None or force or q["id"] in recapture:
            sid = session_for(q)
            sids[q["id"]] = sid
            r = api.post_form(f"/api/assistant/{sid}/message", {"text": q["text"]})
            e = {"id": q["id"], "text": q["text"], "answer": r["answer"], "cards": r["cards"],
                 "trace": r["trace"], "latency_s": r["latency_s"], "cost_usd": r["cost_usd"],
                 "hallucinated": r["hallucinated"], "customer": q.get("customer", a_cfg.get("customer"))}
        e = {**e, "followup_of": q.get("followup_of"), "suggested": q["id"] in a_cfg["suggested"]}
        cited.update(int(c["article_id"]) for c in e["cards"])
        examples.append(e)
    return examples, cited


def capture_photo(api: Api, cfg: dict, fx: Path, out: Path, ec, force: bool) -> tuple[dict, set[int]]:
    """Both photo services on one openly licensed outfit photo; the photo itself is republished with
    its credit. Private evaluation photos are never published."""
    from PIL import Image

    p_cfg = cfg["photo"]
    src = ec.path("raw") / "outfit_photos" / p_cfg["file"]
    credits = {line.split(",")[0]: line for line in (src.parent / "CREDITS.csv").read_text().splitlines()[1:]}
    row = csv_cols(credits[p_cfg["file"]])
    stored = json.loads((fx / "photo.json").read_text()) if (fx / "photo.json").exists() else {}
    if force or not stored.get("snap") or not stored.get("visual_search"):
        files = {"photo": (p_cfg["file"], src.read_bytes(), "image/jpeg")}
        stored = {"visual_search": api.post_form("/api/visual-search",
                                                 {"category": p_cfg["visual_search_category"],
                                                  "box": p_cfg["visual_search_box"]}, files),
                  "snap": api.post_form("/api/snap", {}, files)}
    im = Image.open(src).convert("RGB")
    im.thumbnail((p_cfg["width"], p_cfg["width"] * 4))
    im.save(out / "photo.jpg", format="JPEG", quality=p_cfg["quality"], optimize=True, progressive=True)
    stored["photo"] = {"src": "photo.jpg", "box": [float(v) for v in p_cfg["visual_search_box"].split(",")],
                       "alt": "Saved example photo: a street outfit, with the top framed for search",
                       "credit": f"Photo: {row['title'].removeprefix('File:')} by {row['artist']} ({row['license']}).",
                       "credit_url": row["source"]}
    stored["visual_search_category"] = p_cfg["visual_search_category"]
    ids = {int(m["article_id"]) for m in stored["visual_search"]["matches"]}
    ids |= {int(m["article_id"]) for g in stored["snap"]["garments"] for m in g["matches"]}
    ids |= {int(i["article_id"]) for m in stored["snap"]["complete_the_look"] for i in m["items"]}
    return stored, ids


def csv_cols(line: str) -> dict:
    """CREDITS.csv: file,type,title,artist,license,license_url,source with quoted fields."""
    import csv
    import io
    cols = ["file", "type", "title", "artist", "license", "license_url", "source"]
    return dict(zip(cols, next(csv.reader(io.StringIO(line)))))


def stored_bundle(fx: Path) -> str | None:
    f = fx / "serving.json"
    return json.loads(f.read_text())["meta"]["bundle_version"] if f.exists() else None


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("phase", choices=["build", "sync", "capture"], nargs="?", default="build")
    ap.add_argument("--force", action="store_true",
                    help="re-capture every language-model response (assistant turns, outfit analysis)")
    ap.add_argument("--recapture", default="",
                    help="comma-separated assistant question ids to re-capture, and/or `photo`")
    ap.add_argument("--config", type=Path, default=DEMO_CONFIG)
    a = ap.parse_args(argv)
    cfg = demo_config(a.config)
    if a.phase in ("build", "capture"):
        again = {x.strip() for x in a.recapture.split(",") if x.strip()}
        print(json.dumps(capture(cfg, force=a.force, recapture=again), indent=1))
    if a.phase in ("build", "sync"):
        r = sync(cfg)
        print(f"sync: {len(r['written'])} written, {len(r['kept'])} unchanged, {len(r['removed'])} removed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
